// The places we had before moving to GitHub. Loaded into the shared list once, the first time the site opens with an empty database.
export const SEED = [
 {
  "name": "La Boqueria",
  "type": "eat",
  "area": "old",
  "order": 1,
  "note": "The famous food market. Go before 11 to beat the crowds, skip the touristy front stalls and eat at the counter bars further in (El Quim, Pinotxo).",
  "from": "\"A fantastic food market\"",
  "hours": "Thu–Sat 8:00–20:30 · Sun closed",
  "walk": "About 10 min down La Rambla",
  "lat": 41.3817399,
  "lng": 2.1715853,
  "pid": "ChIJAVoetfeipBIR1a1z3FTGCoY",
  "id": "boqueria"
 },
 {
  "name": "Mercat de Santa Caterina",
  "type": "eat",
  "area": "born",
  "order": 1,
  "note": "The local alternative to La Boqueria, under the colourful wavy roof. Beers and snacks sat up at the bar.",
  "from": "Recommended by a friend",
  "hours": "Thu–Fri 7:30–20:00 · Sat 7:30–15:30 · Sun closed",
  "walk": "About 12 min",
  "lat": 41.3863611,
  "lng": 2.1781566,
  "pid": "ChIJyTz8wvuipBIRfmWLwQzVTc8",
  "id": "caterina"
 },
 {
  "name": "Fismuler",
  "type": "eat",
  "area": "born",
  "order": 3,
  "note": "Daily changing Mediterranean menu from two El Bulli alumni, inside the Hotel REC. The cheesecake is the famous one. The bread and pâté starter is charged per person.",
  "from": "\"Very nice but a bit too cool for its own good\"",
  "hours": "Lunch from 13:00/13:30 · Dinner from 19:00",
  "walk": "About 15 min",
  "lat": 41.3900504,
  "lng": 2.1798497,
  "pid": "ChIJoXV6r_yipBIRd6lCffnj3Hs",
  "bookUrl": "https://www.fismuler.com/en/barcelona/reservar",
  "book": true,
  "id": "fismuler"
 },
 {
  "name": "Park Güell",
  "type": "see",
  "area": "uptown",
  "order": 2,
  "note": "Gaudí's garden, timed entry. It's a steep climb from Lesseps metro; bus 24 from Plaça Catalunya drops you near an entrance. Casa Museu Gaudí is next door.",
  "from": "Recommended twice",
  "hours": "Daily 9:00–19:30",
  "walk": "About 30 min by metro or bus",
  "lat": 41.4144948,
  "lng": 2.1526945,
  "pid": "ChIJq0HUUq6ipBIRWM6qGqALmok",
  "bookUrl": "https://parkguell.barcelona/en",
  "book": true,
  "id": "guell"
 },
 {
  "name": "Time Out Market",
  "type": "eat",
  "area": "added",
  "note": "Time Out Market Barcelona is the top Time Out-curated food and cultural hub in the city, bringing together local chefs, open kitchens, and rooftop terraces under one roof",
  "lat": 41.373741,
  "lng": 2.182803,
  "link": "https://maps.app.goo.gl/zqPHCnu1E7yB8u7T7?g_st=ic",
  "addedBy": "Andrew",
  "createdAt": "2026-10-03T07:45:31.667Z",
  "id": "timeout"
 },
 {
  "name": "Fundació Joan Miró",
  "type": "see",
  "area": "montjuic",
  "order": 2,
  "note": "Most likely the \"amazing gallery\" right next to the Olympic park. Lockers for bags; buying online is slightly cheaper.",
  "from": "\"Definitely worth going to\"",
  "hours": "Thu 10:00–17:00 · Fri–Sat 10:00–20:00 · Sun 10:00–19:00",
  "walk": "Next to the stadium",
  "lat": 41.3686304,
  "lng": 2.1598509,
  "pid": "ChIJLcelLmmipBIRqmlJrcEfypY",
  "id": "miro"
 },
 {
  "name": "MNAC",
  "type": "see",
  "area": "montjuic",
  "order": 3,
  "note": "Catalan art in the big palace on the hill, with a rooftop view over the city. A short walk down from the stadium.",
  "from": "Optional extra",
  "hours": "Thu–Sat 10:00–18:00 · Sun 10:00–15:00",
  "walk": "Short walk from the stadium",
  "lat": 41.3684399,
  "lng": 2.15357,
  "pid": "ChIJMU59xHGipBIRkdwlcgUWAYY",
  "id": "mnac"
 },
 {
  "name": "Bar Mut",
  "type": "eat",
  "area": "uptown",
  "order": 3,
  "note": "Small Catalan market-cooking bar with a Bib Gourmand. Stools at a marble bar, menu chalked on boards. House classic: the fried egg \"carpaccio\" with prawns. Book by email: reservas@barmut.com",
  "from": "Recommended by a Spanish friend",
  "hours": "Daily 13:00–24:00",
  "walk": "About 15 min straight up Pau Claris",
  "lat": 41.3973351,
  "lng": 2.1612629,
  "pid": "ChIJ5_8SapSipBIRQkiXvYQHOmA",
  "bookUrl": "https://barmut.com/",
  "book": true,
  "id": "mut"
 },
 {
  "name": "Picasso Museum",
  "type": "see",
  "area": "born",
  "order": 2,
  "note": "Timed tickets. Follows his work in order, from early academic paintings onwards.",
  "from": "Recommended by a friend",
  "hours": "Thu–Sun 10:00–19:00",
  "walk": "About 15 min",
  "lat": 41.3852706,
  "lng": 2.1809472,
  "pid": "ChIJa-K8mf6ipBIRY8wAB3EeASc",
  "bookUrl": "https://museupicassobcn.cat/",
  "book": true,
  "id": "picasso"
 },
 {
  "name": "Sagrada Família",
  "type": "see",
  "area": "uptown",
  "order": 1,
  "note": "Book on the official site or app only. The inside is the point, so get tickets that go in.",
  "from": "Recommended by a friend",
  "hours": "Thu–Fri 9:00–20:00 · Sat 9:00–18:00 · Sun 10:30–20:00",
  "walk": "About 25 min, or 2 stops on the metro",
  "lat": 41.4036299,
  "lng": 2.1743558,
  "pid": "ChIJk_s92NyipBIRUMnDG8Kq2Js",
  "bookUrl": "https://sagradafamilia.org/en/tickets",
  "book": true,
  "id": "sagrada"
 },
 {
  "name": "Olympic Stadium",
  "type": "see",
  "area": "montjuic",
  "order": 1,
  "note": "The 1992 Olympic park. Takes about 10 minutes, but cool to see.",
  "from": "Recommended by a friend",
  "hours": "Daily 8:00–20:00",
  "walk": "About 25 min by metro and a walk up",
  "lat": 41.3647603,
  "lng": 2.1556418,
  "pid": "ChIJk4ZG4m2ipBIRDMJJqptwPlc",
  "id": "stadium"
 }
];
